query allGames($opponent: String,
                $home: Boolean,
                $score1: Int,
                $score2: Int,
                $result: RESULT,
                $date: DateTime,
                $season: Int,
                $orderBy: GameOrderBy,
                $first: Int,
                $skip: Int
                ) {
	allGames(
        filter: {
            opponent: $opponent,
            home: $home,
            score1: $score1,
            score2: $score2,
            result: $result,
            date: $date,
            season: $season
        },
        orderBy: $orderBy,
        first: $first,
        skip: $skip
    ) {
        id
        opponent
        home
        score1
        score2
        result
        date
        season
	}
    _allGamesMeta {
		count
	}
}